# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - main

name: Deploy Bicep files

variables:
    vmImageName: 'ubuntu-latest'

    azureServiceConnection: 'AzlabBicep'
    resourceGroupName: 'RG-UKS-ENGINE-LZ1-NETWORK-01'
    location: 'uksouth'
    templateFile: 's4hana.solution.bicep'
pool:
    vmImage: $(vmImageName)

steps:
    - task: AzureCLI@2
      inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az group create --name $(resourceGroupName) --location $(location)
            az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)