# Pipline to deploy SAP resources for azure
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: Deploy Bicep files

pool:
  vmImage: ubuntu-latest

variables:
  - name: vm_name
    value: "sapdeployQASS4Q-1"
  - name: rg_name
    value: "RG-S4HANA-S4Q-QAS"

steps:
 - task: AzureCLI@2
   displayName: 'Deploy SAP Environment '
   inputs:
     azureSubscription: 'Rajdeep-AZLAB(a14b6fe5-f739-4b09-a63a-99171f6f2984)'
     scriptType: pscore
     scriptLocation: inlineScript
     inlineScript: 'az deployment sub create --location uksouth  --template-file s4hana.solution.bicep --parameters s4hana.solution.parameters.json'
     workingDirectory: 'Modules/Solution Modules'
     
     
 - task: AzureCLI@2
   displayName: 'Configure Ansible'
   inputs:
    azureSubscription: 'Rajdeep-AZLAB(a14b6fe5-f739-4b09-a63a-99171f6f2984)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm run-command invoke --command-id RunShellScript --name $(vm_name) -g $(rg_name) --scripts "sudo apt update && sudo apt upgrade -y && sudo apt install ansible"'
    powerShellErrorActionPreference: 'silentlyContinue'



