trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: deploy
  steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: $(ServiceConnectioName)
        deploymentName: $(Build.BuildNumber)
        csmFile: Modules/Solution Modules/s4hana.solution.bicep
        overrideParameters: >
          